services:
  gateway:
    build:
      context: ./src/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_SECRETSMANAGER_ENABLED: ${AWS_SECRETSMANAGER_ENABLED:-true}
      AWS_SECRETSMANAGER_SECRET_NAME: ${AWS_SECRETSMANAGER_SECRET_NAME:-bcbs-dev-convai-secrets}
      SERVICE_ORCHESTRATOR_URL: http://orchestrator-agent:8081/orchestrate
    volumes:
      - ${USERPROFILE}/.aws:/root/.aws:ro
    depends_on:
      - orchestrator-agent

  orchestrator-agent:
    build:
      context: ./src/orchestrator-agent
    container_name: orchestrator-agent
    ports:
      - "8081:8081"
    environment:
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_SECRETSMANAGER_ENABLED: ${AWS_SECRETSMANAGER_ENABLED:-true}
      AWS_SECRETSMANAGER_SECRET_NAME: ${AWS_SECRETSMANAGER_SECRET_NAME:-bcbs-dev-convai-secrets}
    volumes:
      - ${USERPROFILE}/.aws:/root/.aws:ro
    depends_on:
      - acct-mgmt-agent

  acct-mgmt-agent:
    build:
      context: ./src/acct-mgmt-agent
    container_name: acct-mgmt-agent
    ports:
      - "8082:8082"
    environment:
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_SECRETSMANAGER_ENABLED: ${AWS_SECRETSMANAGER_ENABLED:-true}
      AWS_SECRETSMANAGER_SECRET_NAME: ${AWS_SECRETSMANAGER_SECRET_NAME:-bcbs-dev-convai-secrets}
    volumes:
      - ${USERPROFILE}/.aws:/root/.aws:ro
