app.name=gateway
server.host=0.0.0.0
server.port=8080
aws.region=us-east-1
http.timeout.seconds=20
service.orchestrator.url=http://localhost:8081/orchestrate
auth.sigv4.enabled=true
auth.sigv4.service=execute-api
development.allow_unsigned_local=true
security.okta.enabled=false
security.okta.issuer=https://your-company.okta.com/oauth2/default
security.okta.audience=api://default
security.okta.jwks_url=https://your-company.okta.com/oauth2/default/v1/keys
security.local.user=personal-laptop-user
